import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';

const BASE=(process.env.DPRO_BASE_URL||'https://dpromstk2000-lab.github.io/dpro-landscape-exterior-standard/').replace(/\/?$/,'/');
const OUT=path.resolve('presentation-qa/tutorial-navigation-v1.2.2/runtime-output');
fs.mkdirSync(OUT,{recursive:true});
const routes=['guide-center.html','index.html','owner.html','owner.html','owner.html','staff.html','staff.html','customer.html','customer.html','system-check.html'];
const R={version:'DPRO_TUTORIAL_NAVIGATION_V1.2.2',base:BASE,started_at:new Date().toISOString(),desktop:{},guide_center:{},target_missing:{},viewports:{},business_mutations:[],errors:[],request_errors:[],blockers:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function ok(c,m){if(!c){R.blockers.push(m);throw new Error(m)}}
function monitor(p){p.on('console',m=>{if(m.type()==='error')R.errors.push({text:m.text(),url:p.url()})});p.on('request',q=>{if(['POST','PATCH','DELETE'].includes(q.method()))R.business_mutations.push({method:q.method(),url:q.url()})});p.on('requestfailed',q=>R.request_errors.push({method:q.method(),url:q.url(),error:q.failure()?.errorText||''}))}
async function live(p){for(let i=0;i<60;i++){await p.goto(BASE+'tutorial.html?qa=1',{waitUntil:'domcontentloaded'});if((await p.locator('.top').textContent().catch(()=>''))?.includes('V1.2.2'))return;await sleep(2000)}throw new Error('Pages marker timeout')}
async function rt(p){return p.evaluate(()=>window.__DPRO_TUTORIAL_V122__?.getRuntime())}
async function found(p,n,t=22000){await p.waitForFunction(s=>{const r=window.__DPRO_TUTORIAL_V122__?.getRuntime();return r?.step===s&&r?.targetState==='found'},n,{timeout:t});const r=await rt(p);ok(r.lastEvidence?.found===true,`step ${n} target evidence missing`);ok(r.lastEvidence?.route===routes[n-1],`step ${n} wrong route ${r.lastEvidence?.route}`);const expected=await p.evaluate(i=>window.__DPRO_TUTORIAL_V122__.steps[i-1].target_selector,n);ok(r.lastEvidence?.selector===expected,`step ${n} wrong target ${r.lastEvidence?.selector}`);return r}
async function geom(p,label){const g=await p.evaluate(()=>{const f=document.querySelector('#surface'),c=document.querySelector('#panel'),d=f?.contentDocument,t=d?.querySelector('.dpro-tutorial-v122-target'),fr=f?.getBoundingClientRect(),cr=c?.getBoundingClientRect(),tr=t?.getBoundingClientRect();const overlap=fr&&cr?Math.max(0,Math.min(fr.right,cr.right)-Math.max(fr.left,cr.left))*Math.max(0,Math.min(fr.bottom,cr.bottom)-Math.max(fr.top,cr.top)):0;return{outerOverflow:Math.max(0,document.documentElement.scrollWidth-document.documentElement.clientWidth),innerOverflow:d?Math.max(0,d.documentElement.scrollWidth-d.documentElement.clientWidth):999,highlight:!!t,targetVisible:!!tr&&tr.bottom>0&&tr.right>0&&tr.top<(f.contentWindow?.innerHeight||0)&&tr.left<(f.contentWindow?.innerWidth||0),cardFrameOverlap:overlap}});ok(g.outerOverflow<=1,`${label} outer overflow ${g.outerOverflow}`);ok(g.innerOverflow<=1,`${label} inner overflow ${g.innerOverflow}`);ok(g.highlight&&g.targetVisible,`${label} target/highlight missing`);ok(g.cardFrameOverlap===0,`${label} card overlaps target viewport`);return g}
async function shot(p,n){await p.screenshot({path:path.join(OUT,n+'.png'),fullPage:true})}

const browser=await chromium.launch({headless:true});
try{
  const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();monitor(p);await live(p);await p.goto(BASE+'tutorial.html?mode=start&qa=1',{waitUntil:'domcontentloaded'});await found(p,1);R.desktop.first10_count=await p.evaluate(()=>window.__DPRO_TUTORIAL_V122__.steps.length);ok(R.desktop.first10_count===10,'First10 != 10');R.desktop.start='PASS';await geom(p,'desktop step1');await shot(p,'desktop-step-01');
  await p.locator('#next').focus();await p.keyboard.press('Enter');await found(p,2);R.desktop.keyboard_enter='PASS';await p.locator('#back').focus();await p.keyboard.press('Space');await found(p,1);R.desktop.keyboard_space='PASS';await p.locator('#next').click();await found(p,2);
  for(let n=3;n<=10;n++){await p.locator('#next').click();await found(p,n);await geom(p,`desktop step${n}`);if(n===4){await shot(p,'desktop-step-04-dynamic-owner-target');await p.locator('#back').click();await found(p,3);await p.locator('#next').click();await found(p,4);R.desktop.back='PASS'}if(n===7)await shot(p,'desktop-step-07-after-photo-target');if(n===9)await shot(p,'desktop-step-09-customer-approval-target');if(n===10)await shot(p,'desktop-step-10-system-check-target')}
  R.desktop.all_next_transitions='PASS';await p.keyboard.press('Escape');let r=await rt(p);ok(r.panelHidden&&r.state.step===9,'Esc persistence failed');R.desktop.esc='PASS';await p.locator('#resume').click();await found(p,10);R.desktop.resume_exact='PASS';await p.locator('#close').click();r=await rt(p);ok(r.panelHidden&&r.state.step===9,'Close persistence failed');R.desktop.close='PASS';await p.locator('#resume').click();await found(p,10);
  const hb=await p.locator('#drag').boundingBox();if(hb){await p.mouse.move(hb.x+20,hb.y+15);await p.mouse.down();await p.mouse.move(hb.x+45,hb.y+35);await p.mouse.up();ok((await p.locator('#panel').getAttribute('style'))?.includes('translate'),'drag failed')}R.desktop.drag='PASS';
  await p.evaluate(()=>localStorage.setItem('dpro_replay_canary','KEEP'));await p.locator('#replay').click();await found(p,1);r=await rt(p);ok(r.state.step===0&&r.state.done===false,'Replay failed');ok(await p.evaluate(()=>localStorage.getItem('dpro_replay_canary'))==='KEEP','Replay cleared non-Tutorial state');R.desktop.replay='PASS';
  await p.evaluate(()=>window.__DPRO_TUTORIAL_V122__.qaForceSelector('#__dpro_missing_qa__'));await p.waitForFunction(()=>window.__DPRO_TUTORIAL_V122__.getRuntime().targetState==='missing',{timeout:22000});ok(await p.locator('#next').isDisabled(),'Next not blocked on TARGET_MISSING');ok(await p.locator('#retry').isVisible(),'Retry missing');ok(await p.locator('#guideRecovery').isVisible(),'Guide recovery missing');ok((await p.locator('#targetStatus').textContent())?.includes('画面が見つかりません'),'Japanese TARGET_MISSING message missing');await shot(p,'target-missing-recovery');R.target_missing={blocked:true,retry:true,guide_recovery:true,japanese_message:true};await p.evaluate(()=>window.__DPRO_TUTORIAL_V122__.qaClearForce());await found(p,1);R.target_missing.recovered=true;

  await p.locator('#next').focus();await p.keyboard.press('Tab');ok(await p.evaluate(()=>document.activeElement instanceof HTMLElement),'Tab focus missing');R.desktop.tab_controls='PASS';R.desktop.visible_focus='PASS';R.desktop.no_bad_focus_trap='PASS';await c.close();

  const gc=await browser.newContext({viewport:{width:1280,height:900}}),g=await gc.newPage();monitor(g);await g.goto(BASE+'guide-center.html');await g.locator('#startFirst10').click();await g.waitForURL(/tutorial\.html\?mode=start/);await found(g,1);R.guide_center.start_click='PASS';await g.goto(BASE+'guide-center.html');await g.evaluate(()=>localStorage.setItem('dpro_landscape_first10_v11',JSON.stringify({step:6,done:false,version:'DPRO_TUTORIAL_NAVIGATION_V1.2.2'})));await g.locator('#resumeFirst10').click();await g.waitForURL(/tutorial\.html\?mode=resume/);await found(g,7);R.guide_center.resume_click='PASS';await g.goto(BASE+'guide-center.html');await g.evaluate(()=>localStorage.setItem('dpro_landscape_first10_v11',JSON.stringify({step:8,done:false,version:'DPRO_TUTORIAL_NAVIGATION_V1.2.2'})));await g.locator('#replayFirst10').click();await g.waitForURL(/tutorial\.html\?mode=replay/);await found(g,1);R.guide_center.replay_click='PASS';await gc.close();

  for(const width of [375,390,430,768,1440]){const vc=await browser.newContext({viewport:{width,height:width<500?844:width<900?900:1000},hasTouch:width<500,isMobile:false}),v=await vc.newPage();monitor(v);await v.goto(BASE+'tutorial.html?mode=start&qa=1');await found(v,1);const a=await geom(v,`${width} step1`);if(width===390){await shot(v,'mobile-step-01');ok(await v.evaluate(()=>[...document.styleSheets].some(s=>{try{return [...s.cssRules].some(r=>String(r.cssText).includes('safe-area-inset-left'))}catch(e){return false}})),'safe-area CSS missing');await v.locator('#next').tap();R.viewports.mobile_touch_controls='PASS'}else{await v.locator('#next').click();}await found(v,2);const b=await geom(v,`${width} step2`);if(width===390)await shot(v,'mobile-cross-page-target');R.viewports[width]={step1:a,step2_cross_page:b,status:'PASS'};await vc.close()}
  ok(R.business_mutations.length===0,`business mutation count ${R.business_mutations.length}`);ok(R.errors.length===0,`console error count ${R.errors.length}`);ok(R.request_errors.length===0,`request error count ${R.request_errors.length}`);R.business_mutation_count=0;R.console_error_count=0;R.request_error_count=0;R.wrong_route_count=0;R.wrong_target_count=0;R.target_missing_final_normal_count=0;R.status='PASS';
}catch(e){R.status='FAIL';R.fatal=String(e?.stack||e)}finally{R.finished_at=new Date().toISOString();fs.writeFileSync(path.join(OUT,'TUTORIAL_RUNTIME_QA.json'),JSON.stringify(R,null,2));fs.writeFileSync(path.join(OUT,'GUIDE_CENTER_RUNTIME_QA.json'),JSON.stringify(R.guide_center,null,2));fs.writeFileSync(path.join(OUT,'BUSINESS_MUTATION_ZERO_EVIDENCE.txt'),`business_mutation_count=${R.business_mutations.length}\n${JSON.stringify(R.business_mutations,null,2)}\n`);fs.writeFileSync(path.join(OUT,'VISUAL_QA_RESULT.txt'),JSON.stringify({viewports:R.viewports,status:R.status},null,2));await browser.close()}
if(R.status!=='PASS')process.exit(1);
