import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
const ROOT=process.env.LOCAL_ROOT_URL||'http://127.0.0.1:4173/';
const OUT=path.resolve('presentation-qa/support-sync-v1.2.2/runtime-output');
fs.mkdirSync(OUT,{recursive:true});
const jobs=[
  {name:'quick',route:'site/quick-start.html?pdf=1',pages:3,out:'site/DPRO_LANDSCAPE_EXTERIOR_QUICK_START_MASTER_V1.2.2_20260905.pdf'},
  {name:'detailed',route:'site/detailed-manual.html?pdf=1',pages:10,out:'site/DPRO_LANDSCAPE_EXTERIOR_DETAILED_MANUAL_MASTER_V1.2.2_20260905.pdf'}
];
const browser=await chromium.launch({headless:true});
let failed=false;
for(const job of jobs){const ctx=await browser.newContext({viewport:{width:900,height:1200}});const page=await ctx.newPage();const consoleErrors=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});try{await page.goto(ROOT+job.route,{waitUntil:'networkidle',timeout:60000});await page.emulateMedia({media:'print'});await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:30000});const qa=await page.evaluate(expected=>{const pages=[...document.querySelectorAll('.page')];const details=pages.map((sec,i)=>{const sr=sec.getBoundingClientRect();const foot=sec.querySelector('.foot');const fr=foot?.getBoundingClientRect();const children=[...sec.children].filter(x=>!x.classList.contains('foot'));const maxBottom=Math.max(sr.top,...children.map(x=>x.getBoundingClientRect().bottom));const textOverflow=[...sec.querySelectorAll('h1,h2,h3,p,li,.box,.green,.warn')].filter(el=>el.scrollWidth>el.clientWidth+1).length;const outOfPage=[...sec.querySelectorAll('h1,h2,h3,p,li,img,.box,.green,.warn')].filter(el=>{const r=el.getBoundingClientRect();return r.left<sr.left-1||r.right>sr.right+1||r.top<sr.top-1||r.bottom>sr.bottom+1}).length;return{page:i+1,scrollWidth:sec.scrollWidth,clientWidth:sec.clientWidth,scrollHeight:sec.scrollHeight,clientHeight:sec.clientHeight,overflowX:Math.max(0,sec.scrollWidth-sec.clientWidth),overflowY:Math.max(0,sec.scrollHeight-sec.clientHeight),contentFootOverlap:fr?Math.max(0,maxBottom-(fr.top-6)):0,textOverflow,outOfPage}});return{count:pages.length,expected,details,shots:[...document.querySelectorAll('img.shot')].map(i=>({src:i.src,w:i.naturalWidth,h:i.naturalHeight})),allImages:[...document.images].map(i=>({src:i.src,complete:i.complete,w:i.naturalWidth,h:i.naturalHeight}))}},job.pages);if(qa.count!==job.pages||qa.details.some(x=>x.overflowX>1||x.overflowY>1||x.contentFootOverlap>1||x.textOverflow>0||x.outOfPage>0)||qa.shots.some(x=>!x.w||!x.h)||qa.allImages.some(x=>!x.complete||!x.w||!x.h)){failed=true;qa.status='FAIL'}else qa.status='PASS';qa.console_errors=consoleErrors;fs.writeFileSync(path.join(OUT,job.name==='quick'?'QUICK_LAYOUT_QA.json':'DETAILED_LAYOUT_QA.json'),JSON.stringify(qa,null,2));if(qa.status!=='PASS')throw new Error(`${job.name} layout QA failed`);await page.pdf({path:job.out,format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'0',right:'0',bottom:'0',left:'0'}})}catch(e){failed=true;fs.writeFileSync(path.join(OUT,job.name.toUpperCase()+'_BUILD_ERROR.txt'),String(e?.stack||e))}finally{await ctx.close()}}
await browser.close();
if(failed)process.exit(1);
